name: 'Chimera Ant Development Environment'
description: "Chimera Ant's development environment"
author: 'Chimera Ant'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'briefcase'
  color: 'green'
