name: 'build-test-release'
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint-and-check-dist:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
      - run: pnpm lint
      - run: pnpm build:ci
      - name: Compare the expected and actual dist/ directories
        run: |
          if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build.  See status below:"
            git diff
            exit 1
          fi
        id: diff

  lint-and-check-dist-no-cache:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          use_cache: false
      - run: pnpm lint
      - run: pnpm build:ci
      - name: Compare the expected and actual dist/ directories
        run: |
          if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build.  See status below:"
            git diff
            exit 1
          fi
        id: diff

  lint-and-check-dist-cachix:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
      - uses: cachix/cachix-action@v12
        with:
          name: aabccd021nixgithubactionstest
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - uses: actions/cache@v3
        with:
          path: ~/.local/share/pnpm/store/v3
          key: ${{ runner.os }}-pnpm-cachix-${{ hashFiles('**/pnpm-lock.yaml') }}
      - run: curl -sfL https://direnv.net/install.sh | bash
      - run: direnv allow
      - run: direnv export gha >> "$GITHUB_ENV"
      - run: pnpm lint
      - run: pnpm build:ci
      - name: Compare the expected and actual dist/ directories
        run: |
          if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build.  See status below:"
            git diff
            exit 1
          fi
        id: diff

  test:
    timeout-minutes: 5
    runs-on: ubuntu-22.04
    needs: lint-and-check-dist
    steps:
      - uses: actions/checkout@v3
      - uses: ./
      - run: playwright pdf google.com a.pdf

  test-no-cache:
    timeout-minutes: 5
    runs-on: ubuntu-22.04
    needs: lint-and-check-dist-no-cache
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          use_cache: false
      - run: playwright pdf google.com a.pdf

  test-cachix:
    timeout-minutes: 5
    runs-on: ubuntu-22.04
    needs: lint-and-check-dist-cachix
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
      - uses: cachix/cachix-action@v12
        with:
          name: aabccd021nixgithubactionstest
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - uses: actions/cache@v3
        with:
          path: ~/.local/share/pnpm/store/v3
          key: ${{ runner.os }}-pnpm-cachix-${{ hashFiles('**/pnpm-lock.yaml') }}
      - run: curl -sfL https://direnv.net/install.sh | bash
      - run: direnv allow
      - run: direnv export gha >> "$GITHUB_ENV"
      - run: playwright pdf google.com a.pdf

  release:
    timeout-minutes: 5
    needs: [ test, test-cachix, test-no-cache ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
      - run: pnpm semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
